spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: demo@gmail.com
    password: njk dfd dfsgs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
        